language: node_js
sudo: false
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add babel-cli
  - yarn global add @semantic-release/git semantic-release
after_success:
  - yarn copy
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
