version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    default_assignees:
      - "markusguenther"
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
    default_assignees:
      - "markusguenther"
