Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Unikka.Slick':
          - 'NodeTypes/*'
          - 'Main'
    fusion:
      autoInclude:
        Unikka.Slick: true
  Fusion:
    defaultContext:
      'Unikka.Slick': 'Unikka\Slick\Eel\Helper\SlickEelHelper'
