Unikka:
  Slick:
    # include the theme css file from slick
    theme: true
    backend:
      # disables autoplay in backend
      disableAutoplay: true
    # breakpoints for the responsive tab
    responsive:
      sm: 576
      md: 768
      lg: 992
      xl: 1200
