Unikka:
  Slick:
    # include the theme css file from slick
    theme: true
    backend:
      # disables autoplay in backend
      disableAutoplay: true
      # disables tabbing and arrow key navigation in backend
      disableAccessibility: true
      # disables mouse dragging in backend
      disableDraggable: true
      # disables swiping in backend
      disableSwipe: true
      # disables animation duration in backend
      # important to prevent glitches with the inline editing
      disableAnitmationSpeed: true
    # breakpoints for the responsive tab
    responsive:
      sm: 576
      md: 768
      lg: 992
      xl: 1200
